### ISSUE TITLE
Undefined constant SCRIPT_VERSION

### ISSUE THREAD

**Issue by Mte90** [voceconnect/voce-post-expiration#2]
I get that error:
`Notice: Use of undefined constant SCRIPT_VERSION - assumed 'SCRIPT_VERSION' in /htdocs/wp-content/plugins/datask/composer/voceconnect/voce-post-expiration/voce-post-expiration.php on line 44`

**Comment by smccafferty** [comment]
Generally a `SCRIPT_VERSION` constant is defined in wp-config.php in order to apply it across all of your enqueued styles/scripts for versioning/cache busting purposes. Adding `define('SCRIPT_VERSION', '20160907120810');` to your wp-config.php should resolve your issue.

**Comment by Mte90** [comment]
Well it's the first time that I see this constant, but I am integrating this library in my plugin and I don't want to receive alerts from my user of this error.

**Comment by matgargano** [comment]
You can always add to your library
```
defined('SCRIPT_VERSION') or define('SCRIPT_VERSION', '20160917');
```
